### ISSUE TITLE
Always showing an update

### ISSUE THREAD

**Issue by maicol07** [Lacro59/playnite-successstory-plugin#123]
Hi,

I've updated to 1.4.4 and it shows that `1.4.4` (it says I have `v1.4.4`) is available to update... Can you fix this?

Thanks

**Comment by kwilliams1987** [comment]
Same issue here, originally reported it to Josef but he said to report here: https://github.com/JosefNemec/Playnite/issues/2369

**Comment by joyrider3774** [comment]
https://playnite.link/forum/thread-514-post-4369.html#pid4369

**Comment by Lacro59** [comment]
Here with the good plugin id : https://playnite.link/forum/thread-275-post-5012.html#pid5012

**Comment by Kdog88** [comment]
hi, i have the same issue as well.

**Comment by Lacro59** [comment]
resolved

**Comment by maicol07** [comment]
@Lacro59 this isn't solved. The update notification is still there
